### ISSUE TITLE
Errors parsing configuration / Invalid color name

### ISSUE THREAD

**Issue by nertzy** [tinted-theming/tinted-kitty#1] opened 2024-07-26 21:51 UTC
Commit https://github.com/tinted-theming/tinted-kitty/commit/86288de7ec45455d67a8e6bdf58e46909a03368b seems to have broken themes by setting color9 through color14 to `#`.

```
Errors parsing configuration


In file /Users/grant/.config/kitty/kitty.conf:
2561:Invalid color name: # in line: color9 #

2562:Invalid color name: # in line: color10 #

2563:Invalid color name: # in line: color11 #

2564:Invalid color name: # in line: color12 #

2565:Invalid color name: # in line: color13 #

2566:Invalid color name: # in line: color14 #

Press Enter or Esc to exit
```

**Comment by JamyGolden** [comment] 2024-09-02 18:49
Thanks for the issue. I wasn't tagged in the PR so I didn't get notified, but I've just merged a github action which will auto tag me in issues from now on.

This is a weird bug. I'm not sure exactly what the issue is. The builder sometimes generates without these values and other times with the values. I've recreated this problem with both builder-rust and builder-go locally. 

I've fixed the theme files in the current `main` branch, but the bug itself isn't fixed. I'll look into it and close this issue once I've found the root cause.

**Comment by JamyGolden** [comment] 2024-09-02 19:04
Fixed it, the `supported-system` properties were left out of the `templates/config.yaml` file so there was a race-condition for the builders building the `base16.mustache` with base16 scheme and the `base24.mustache` template with base16 scheme (which includes colors base16 doesn't have so it would render nothing). 

Thanks again for the issue.

**Closed as completed by JamyGolden** 2024-09-02 19:04 UTC
